### ISSUE TITLE
The client doesn't return correct value when used with unleash-edge

### ISSUE THREAD

**Issue by JonasBak** [Unleash/unleash-client-dotnet#165]
**Describe the bug**
We have a toggle in three environments (dev, test, prod). The toggle is turned on (100%) in dev, and off (0%) in test and prod.

We use a token with access to the dev environment. When we configure the client to use unleash directly it works as expected and the toggle evaluates as `true`, but if we change the url to our unleash-edge instance, it evaluates as `false`.

I have recreated it with the ["Synchronous startup" example](https://www.nuget.org/packages/Unleash.Client/). I thinks this is an issue with the dotnet client, as when i test the golang package with the same token and url using the [SimpleUsage example here](https://pkg.go.dev/github.com/Unleash/unleash-client-go/v3#example-package-SimpleUsage), it works as expected.

I have also tried calling `/api/client/features` on the unleash-edge instance directly with the same token, and it returns the flag with `"enabled": true`.

**To Reproduce**

1. Create a toggle in three environments
2. Enable the toggle in one environment
3. Create a token for that environment
4. Deploy an unleash-edge instance
5. Configure the client to use the token and unleash-edge, check if the feature is enabled using `unleash.IsEnabled`
6. Change the url to use unleash without unleash-edge and try again

**Expected behavior**
I expect the client to return the same value as configured upstream and as returned by other clients.

**Screenshots**

**Additional context**
This is using version 3.3.3 of the client and v13.0.0 of unleash-edge.

The unleash-edge deployment basically looks like this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unleash-edge
  namespace: unleash
spec:
  selector:
    matchLabels:
      app: unleash-edge
  template:
    metadata:
      labels:
        app: unleash-edge
    spec:
      containers:
      - name: unleash-edge
        image: docker.io/unleashorg/unleash-edge:v13.0.0
        args:
        - edge
        env:
        - name: UPSTREAM_URL
          value: "https://eu.app.unleash-hosted.com/OUR_UPSTREAM_URL"
        ports:
        - containerPort: 3063
          name: http
```

This is tested both with and without setting a `SERVICE_ACCOUNT_TOKEN` environment variable.
